import { Activity, DashboardStats, Lead } from '@/lib/types';

type LeadQuery = {
  search?: string;
  status?: string;
  priority?: string;
  city?: string;
  state?: string;
  industry?: string;
  sort?: string;
  dir?: 'asc' | 'desc';
};

const MOCK_LEADS: Lead[] = [
  {
    id: 1,
    businessName: 'Green Horizon Lawn Care',
    contactName: 'Evan Torres',
    phone: '(816) 555-1001',
    email: 'evan@greenhorizon.com',
    website: 'https://greenhorizon.example',
    facebookPage: 'https://facebook.com/greenhorizon',
    address: '1821 Oak Street',
    city: 'Kansas City',
    state: 'MO',
    industry: 'Lawn Care',
    currentWebsiteQuality: 'Average',
    hasWebsite: 'Yes',
    hasFacebookPage: 'Yes',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'SEO and lead forms',
    suggestedOffer: 'Growth package',
    estimatedDealValue: 1800,
    leadSource: 'Website',
    leadStatus: 'Interested',
    priority: 'Hot',
    lastContactedDate: '2026-05-24',
    nextFollowUpDate: '2026-05-27',
    notes: 'Asked for lawn and irrigation pages.',
    painPoints: 'Low search visibility',
    personalizedPitch: 'Focused local growth plan.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'High',
    websitePackageInterest: 'High',
    crmPackageInterest: 'Medium',
    tags: ['landscaping', 'seo'],
    createdDate: '2026-05-02 10:15:00',
    updatedDate: '2026-05-24 13:10:00',
  },
  {
    id: 2,
    businessName: 'Summit Stone and Deck',
    contactName: 'Alyssa Reed',
    phone: '(913) 555-1002',
    email: 'alyssa@summitstone.example',
    website: 'https://summitstone.example',
    facebookPage: '',
    address: '4412 Mission Road',
    city: 'Overland Park',
    state: 'KS',
    industry: 'Contractor',
    currentWebsiteQuality: 'Poor',
    hasWebsite: 'Yes',
    hasFacebookPage: 'No',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Gallery and quote funnel',
    suggestedOffer: 'Website rebuild',
    estimatedDealValue: 4200,
    leadSource: 'Referral',
    leadStatus: 'Proposal sent',
    priority: 'Urgent',
    lastContactedDate: '2026-05-25',
    nextFollowUpDate: '2026-05-28',
    notes: 'Needs proposal by end of week.',
    painPoints: 'No mobile conversion',
    personalizedPitch: 'Visual portfolio with conversion flow.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Medium',
    websitePackageInterest: 'High',
    crmPackageInterest: 'Low',
    tags: ['contractor', 'proposal'],
    createdDate: '2026-05-06 09:05:00',
    updatedDate: '2026-05-25 16:20:00',
  },
  {
    id: 3,
    businessName: 'Blue Sky Auto Repair',
    contactName: 'Nina Patel',
    phone: '(816) 555-1003',
    email: 'nina@blueskyauto.example',
    website: 'https://blueskyauto.example',
    facebookPage: 'https://facebook.com/blueskyauto',
    address: '9731 Main Street',
    city: 'Lee\'s Summit',
    state: 'MO',
    industry: 'Auto Repair',
    currentWebsiteQuality: 'Good',
    hasWebsite: 'Yes',
    hasFacebookPage: 'Yes',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Review automation',
    suggestedOffer: 'CRM and follow ups',
    estimatedDealValue: 2400,
    leadSource: 'Google',
    leadStatus: 'Contacted',
    priority: 'Warm',
    lastContactedDate: '2026-05-26',
    nextFollowUpDate: '2026-05-29',
    notes: 'Wants missed call text back flow.',
    painPoints: 'Low repeat visits',
    personalizedPitch: 'Retention playbook for service reminders.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Medium',
    websitePackageInterest: 'Low',
    crmPackageInterest: 'High',
    tags: ['auto', 'retention'],
    createdDate: '2026-05-08 11:45:00',
    updatedDate: '2026-05-26 09:30:00',
  },
  {
    id: 4,
    businessName: 'Cedar Ridge Cleaning',
    contactName: 'Jordan Miles',
    phone: '(816) 555-1004',
    email: 'jordan@cedarridgeclean.example',
    website: '',
    facebookPage: 'https://facebook.com/cedarridgeclean',
    address: '2108 Walnut Avenue',
    city: 'Kansas City',
    state: 'MO',
    industry: 'Cleaning Company',
    currentWebsiteQuality: 'None',
    hasWebsite: 'No',
    hasFacebookPage: 'Yes',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Starter site and booking form',
    suggestedOffer: 'Starter package',
    estimatedDealValue: 1200,
    leadSource: 'Facebook',
    leadStatus: 'New',
    priority: 'Warm',
    lastContactedDate: '',
    nextFollowUpDate: '2026-05-27',
    notes: 'Brand new owner operator.',
    painPoints: 'No online presence',
    personalizedPitch: 'Launch package with local profile setup.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Low',
    websitePackageInterest: 'High',
    crmPackageInterest: 'Low',
    tags: ['cleaning', 'startup'],
    createdDate: '2026-05-26 08:15:00',
    updatedDate: '2026-05-26 08:15:00',
  },
  {
    id: 5,
    businessName: 'Prime Edge Roofing',
    contactName: 'Scott White',
    phone: '(913) 555-1005',
    email: 'scott@primeedgeroofing.example',
    website: 'https://primeedge.example',
    facebookPage: '',
    address: '5810 W 95th Street',
    city: 'Overland Park',
    state: 'KS',
    industry: 'Contractor',
    currentWebsiteQuality: 'Average',
    hasWebsite: 'Yes',
    hasFacebookPage: 'No',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Paid lead funnel',
    suggestedOffer: 'Marketing plus CRM',
    estimatedDealValue: 5200,
    leadSource: 'Outbound',
    leadStatus: 'Meeting scheduled',
    priority: 'Hot',
    lastContactedDate: '2026-05-25',
    nextFollowUpDate: '2026-05-30',
    notes: 'Demo call booked for Friday.',
    painPoints: 'Lead response time',
    personalizedPitch: 'Speed to lead workflow with SMS.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'High',
    websitePackageInterest: 'Medium',
    crmPackageInterest: 'High',
    tags: ['roofing', 'meeting'],
    createdDate: '2026-05-03 14:22:00',
    updatedDate: '2026-05-25 12:44:00',
  },
  {
    id: 6,
    businessName: 'River Town Salon',
    contactName: 'Keisha Long',
    phone: '(816) 555-1006',
    email: 'keisha@rivertownsalon.example',
    website: 'https://rivertownsalon.example',
    facebookPage: 'https://facebook.com/rivertownsalon',
    address: '117 River Market Lane',
    city: 'Kansas City',
    state: 'MO',
    industry: 'Salon',
    currentWebsiteQuality: 'Good',
    hasWebsite: 'Yes',
    hasFacebookPage: 'Yes',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Retention campaigns',
    suggestedOffer: 'Email and SMS follow up',
    estimatedDealValue: 1600,
    leadSource: 'Google',
    leadStatus: 'Won',
    priority: 'Warm',
    lastContactedDate: '2026-05-20',
    nextFollowUpDate: '',
    notes: 'Signed monthly plan.',
    painPoints: 'Rebook rate',
    personalizedPitch: 'Stylist specific reminder flows.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Medium',
    websitePackageInterest: 'Low',
    crmPackageInterest: 'Medium',
    tags: ['salon', 'won'],
    createdDate: '2026-05-01 09:10:00',
    updatedDate: '2026-05-20 15:30:00',
  },
  {
    id: 7,
    businessName: 'Metro Fleet Wash',
    contactName: 'Chris Howard',
    phone: '(816) 555-1007',
    email: 'chris@metrofleetwash.example',
    website: '',
    facebookPage: '',
    address: '8290 Truman Road',
    city: 'Independence',
    state: 'MO',
    industry: 'Cleaning Company',
    currentWebsiteQuality: 'None',
    hasWebsite: 'No',
    hasFacebookPage: 'No',
    googleBusinessProfile: 'Unclaimed',
    serviceOpportunity: 'Basic web and local listings',
    suggestedOffer: 'Launch package',
    estimatedDealValue: 900,
    leadSource: 'Cold call',
    leadStatus: 'No answer',
    priority: 'Cold',
    lastContactedDate: '2026-05-22',
    nextFollowUpDate: '2026-06-01',
    notes: 'Left voicemail twice.',
    painPoints: 'No online channel',
    personalizedPitch: 'Simple lead capture setup.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Low',
    websitePackageInterest: 'Medium',
    crmPackageInterest: 'Low',
    tags: ['cold', 'voicemail'],
    createdDate: '2026-05-10 10:40:00',
    updatedDate: '2026-05-22 17:02:00',
  },
  {
    id: 8,
    businessName: 'West Park Dentistry',
    contactName: 'Dr. Ben Cole',
    phone: '(913) 555-1008',
    email: 'ben@westparkdental.example',
    website: 'https://westparkdental.example',
    facebookPage: 'https://facebook.com/westparkdental',
    address: '7422 State Line Road',
    city: 'Prairie Village',
    state: 'KS',
    industry: 'Dental',
    currentWebsiteQuality: 'Average',
    hasWebsite: 'Yes',
    hasFacebookPage: 'Yes',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Appointment funnel',
    suggestedOffer: 'Premium growth package',
    estimatedDealValue: 6800,
    leadSource: 'Referral',
    leadStatus: 'Interested',
    priority: 'Urgent',
    lastContactedDate: '2026-05-26',
    nextFollowUpDate: '2026-05-27',
    notes: 'Needs family plan landing pages.',
    painPoints: 'No conversion tracking',
    personalizedPitch: 'High intent service page stack.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'High',
    websitePackageInterest: 'High',
    crmPackageInterest: 'Medium',
    tags: ['healthcare', 'high value'],
    createdDate: '2026-05-04 13:15:00',
    updatedDate: '2026-05-26 11:55:00',
  },
  {
    id: 9,
    businessName: 'Oakline Plumbing',
    contactName: 'Mason Bell',
    phone: '(816) 555-1009',
    email: 'mason@oaklineplumbing.example',
    website: 'https://oaklineplumbing.example',
    facebookPage: '',
    address: '3301 N Oak Trafficway',
    city: 'Kansas City',
    state: 'MO',
    industry: 'Contractor',
    currentWebsiteQuality: 'Good',
    hasWebsite: 'Yes',
    hasFacebookPage: 'No',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Service area pages',
    suggestedOffer: 'SEO package',
    estimatedDealValue: 3100,
    leadSource: 'Google',
    leadStatus: 'Demo website sent',
    priority: 'Hot',
    lastContactedDate: '2026-05-23',
    nextFollowUpDate: '2026-05-27',
    notes: 'Asked for financing CTA.',
    painPoints: 'Low map pack rank',
    personalizedPitch: 'Location page strategy.',
    demoWebsiteUrl: 'https://demo.example/oakline',
    crmDemoUrl: '',
    marketingPackageInterest: 'High',
    websitePackageInterest: 'Medium',
    crmPackageInterest: 'Low',
    tags: ['demo sent', 'plumbing'],
    createdDate: '2026-05-09 08:50:00',
    updatedDate: '2026-05-23 14:10:00',
  },
  {
    id: 10,
    businessName: 'Golden Hour Catering',
    contactName: 'Maya Rivers',
    phone: '(913) 555-1010',
    email: 'maya@goldenhourcatering.example',
    website: 'https://goldenhourcatering.example',
    facebookPage: 'https://facebook.com/goldenhourcatering',
    address: '11516 Metcalf Avenue',
    city: 'Overland Park',
    state: 'KS',
    industry: 'Restaurant',
    currentWebsiteQuality: 'Average',
    hasWebsite: 'Yes',
    hasFacebookPage: 'Yes',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Event lead intake flow',
    suggestedOffer: 'Catering funnel package',
    estimatedDealValue: 2700,
    leadSource: 'Instagram',
    leadStatus: 'Follow up needed',
    priority: 'Warm',
    lastContactedDate: '2026-05-21',
    nextFollowUpDate: '2026-05-27',
    notes: 'Requested event package matrix.',
    painPoints: 'Manual quote process',
    personalizedPitch: 'Automated inquiry workflow.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Medium',
    websitePackageInterest: 'Medium',
    crmPackageInterest: 'Medium',
    tags: ['catering', 'follow up'],
    createdDate: '2026-05-11 16:32:00',
    updatedDate: '2026-05-21 10:04:00',
  },
  {
    id: 11,
    businessName: 'Atlas Fitness Studio',
    contactName: 'Priya Shah',
    phone: '(816) 555-1011',
    email: 'priya@atlasfit.example',
    website: 'https://atlasfit.example',
    facebookPage: 'https://facebook.com/atlasfit',
    address: '6910 Wornall Road',
    city: 'Kansas City',
    state: 'MO',
    industry: 'Gym',
    currentWebsiteQuality: 'Good',
    hasWebsite: 'Yes',
    hasFacebookPage: 'Yes',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Membership nurture',
    suggestedOffer: 'CRM automation package',
    estimatedDealValue: 2200,
    leadSource: 'Referral',
    leadStatus: 'Ready to contact',
    priority: 'Warm',
    lastContactedDate: '',
    nextFollowUpDate: '2026-05-28',
    notes: 'Asked for trial offer sequence.',
    painPoints: 'Drop off after first month',
    personalizedPitch: 'Retention workflows for memberships.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Low',
    websitePackageInterest: 'Low',
    crmPackageInterest: 'High',
    tags: ['fitness', 'automation'],
    createdDate: '2026-05-15 09:38:00',
    updatedDate: '2026-05-15 09:38:00',
  },
  {
    id: 12,
    businessName: 'Northland Pest Control',
    contactName: 'Derek Young',
    phone: '(816) 555-1012',
    email: 'derek@northlandpest.example',
    website: 'https://northlandpest.example',
    facebookPage: '',
    address: '4521 N Antioch Road',
    city: 'Gladstone',
    state: 'MO',
    industry: 'General Service',
    currentWebsiteQuality: 'Poor',
    hasWebsite: 'Yes',
    hasFacebookPage: 'No',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Lead response automation',
    suggestedOffer: 'CRM starter',
    estimatedDealValue: 1500,
    leadSource: 'Outbound',
    leadStatus: 'Needs research',
    priority: 'Cold',
    lastContactedDate: '',
    nextFollowUpDate: '2026-05-31',
    notes: 'Need competitor snapshot.',
    painPoints: 'Slow call response',
    personalizedPitch: 'Lead triage with missed call text back.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Low',
    websitePackageInterest: 'Low',
    crmPackageInterest: 'Medium',
    tags: ['research', 'service'],
    createdDate: '2026-05-13 13:49:00',
    updatedDate: '2026-05-13 13:49:00',
  },
  {
    id: 13,
    businessName: 'Elm Street Pediatrics',
    contactName: 'Laura Kim',
    phone: '(913) 555-1013',
    email: 'laura@elmstreetpeds.example',
    website: 'https://elmstreetpeds.example',
    facebookPage: '',
    address: '6400 Antioch Road',
    city: 'Merriam',
    state: 'KS',
    industry: 'Healthcare',
    currentWebsiteQuality: 'Average',
    hasWebsite: 'Yes',
    hasFacebookPage: 'No',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'New patient flow',
    suggestedOffer: 'Website and automation',
    estimatedDealValue: 3900,
    leadSource: 'Google',
    leadStatus: 'Lost',
    priority: 'Warm',
    lastContactedDate: '2026-05-19',
    nextFollowUpDate: '',
    notes: 'Chose in house team.',
    painPoints: 'Scheduling friction',
    personalizedPitch: 'Family onboarding journey.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Medium',
    websitePackageInterest: 'High',
    crmPackageInterest: 'Low',
    tags: ['lost'],
    createdDate: '2026-05-05 12:15:00',
    updatedDate: '2026-05-19 09:03:00',
  },
  {
    id: 14,
    businessName: 'True North Realty Group',
    contactName: 'Hannah Brooks',
    phone: '(816) 555-1014',
    email: 'hannah@truenorthrealty.example',
    website: 'https://truenorthrealty.example',
    facebookPage: 'https://facebook.com/truenorthrealty',
    address: '401 Walnut Street',
    city: 'Kansas City',
    state: 'MO',
    industry: 'Real Estate',
    currentWebsiteQuality: 'Good',
    hasWebsite: 'Yes',
    hasFacebookPage: 'Yes',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Neighborhood landing pages',
    suggestedOffer: 'Content and SEO',
    estimatedDealValue: 3300,
    leadSource: 'LinkedIn',
    leadStatus: 'Interested',
    priority: 'Hot',
    lastContactedDate: '2026-05-26',
    nextFollowUpDate: '2026-05-28',
    notes: 'Wants city specific pages.',
    painPoints: 'Lead quality inconsistency',
    personalizedPitch: 'Intent based local page strategy.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'High',
    websitePackageInterest: 'Medium',
    crmPackageInterest: 'Low',
    tags: ['real estate', 'seo'],
    createdDate: '2026-05-07 11:20:00',
    updatedDate: '2026-05-26 12:06:00',
  },
  {
    id: 15,
    businessName: 'Stone Creek Insurance',
    contactName: 'Wes Ford',
    phone: '(913) 555-1015',
    email: 'wes@stonecreekins.example',
    website: 'https://stonecreekins.example',
    facebookPage: '',
    address: '8711 Shawnee Mission Pkwy',
    city: 'Merriam',
    state: 'KS',
    industry: 'Insurance',
    currentWebsiteQuality: 'Average',
    hasWebsite: 'Yes',
    hasFacebookPage: 'No',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Renewal campaign automation',
    suggestedOffer: 'CRM growth package',
    estimatedDealValue: 2800,
    leadSource: 'Email outreach',
    leadStatus: 'Contacted',
    priority: 'Warm',
    lastContactedDate: '2026-05-24',
    nextFollowUpDate: '2026-05-29',
    notes: 'Interested in policy renewal reminders.',
    painPoints: 'Manual renewal tracking',
    personalizedPitch: 'Renewal first automation map.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Medium',
    websitePackageInterest: 'Low',
    crmPackageInterest: 'High',
    tags: ['insurance', 'renewals'],
    createdDate: '2026-05-12 10:09:00',
    updatedDate: '2026-05-24 15:47:00',
  },
  {
    id: 16,
    businessName: 'Harbor Church Community',
    contactName: 'Pastor Eli Grant',
    phone: '(816) 555-1016',
    email: 'eli@harborchurch.example',
    website: 'https://harborchurch.example',
    facebookPage: 'https://facebook.com/harborchurch',
    address: '2300 East 39th Street',
    city: 'Kansas City',
    state: 'MO',
    industry: 'Nonprofit',
    currentWebsiteQuality: 'Poor',
    hasWebsite: 'Yes',
    hasFacebookPage: 'Yes',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Events and donation pages',
    suggestedOffer: 'Community package',
    estimatedDealValue: 1300,
    leadSource: 'Referral',
    leadStatus: 'Not a fit',
    priority: 'Cold',
    lastContactedDate: '2026-05-17',
    nextFollowUpDate: '',
    notes: 'Budget too low right now.',
    painPoints: 'Outdated event pages',
    personalizedPitch: 'Simple events and volunteer signup.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Low',
    websitePackageInterest: 'Medium',
    crmPackageInterest: 'Low',
    tags: ['nonprofit'],
    createdDate: '2026-05-14 09:20:00',
    updatedDate: '2026-05-17 17:31:00',
  },
  {
    id: 17,
    businessName: 'Main Street Pet Clinic',
    contactName: 'Dr. Cara Lewis',
    phone: '(816) 555-1017',
    email: 'cara@mainstreetpet.example',
    website: 'https://mainstreetpet.example',
    facebookPage: 'https://facebook.com/mainstreetpet',
    address: '510 Main Street',
    city: 'Liberty',
    state: 'MO',
    industry: 'Healthcare',
    currentWebsiteQuality: 'Good',
    hasWebsite: 'Yes',
    hasFacebookPage: 'Yes',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Online bookings',
    suggestedOffer: 'Website optimization',
    estimatedDealValue: 2100,
    leadSource: 'Google',
    leadStatus: 'Demo website started',
    priority: 'Hot',
    lastContactedDate: '2026-05-26',
    nextFollowUpDate: '2026-05-30',
    notes: 'Requested pet wellness CTA.',
    painPoints: 'Low online booking rate',
    personalizedPitch: 'Booking first homepage structure.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Medium',
    websitePackageInterest: 'High',
    crmPackageInterest: 'Low',
    tags: ['pet clinic', 'demo'],
    createdDate: '2026-05-16 14:05:00',
    updatedDate: '2026-05-26 10:12:00',
  },
  {
    id: 18,
    businessName: 'Citywide Electrical',
    contactName: 'Noah Pierce',
    phone: '(913) 555-1018',
    email: 'noah@citywideelectrical.example',
    website: 'https://citywideelectrical.example',
    facebookPage: '',
    address: '11800 College Blvd',
    city: 'Overland Park',
    state: 'KS',
    industry: 'Contractor',
    currentWebsiteQuality: 'Average',
    hasWebsite: 'Yes',
    hasFacebookPage: 'No',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Commercial lead routing',
    suggestedOffer: 'CRM pro package',
    estimatedDealValue: 4500,
    leadSource: 'Outbound',
    leadStatus: 'Ready to contact',
    priority: 'Urgent',
    lastContactedDate: '',
    nextFollowUpDate: '2026-05-27',
    notes: 'Requested proposal examples.',
    painPoints: 'No central pipeline',
    personalizedPitch: 'Pipeline and reminder automation.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Medium',
    websitePackageInterest: 'Medium',
    crmPackageInterest: 'High',
    tags: ['electrical', 'pipeline'],
    createdDate: '2026-05-18 08:05:00',
    updatedDate: '2026-05-18 08:05:00',
  },
  {
    id: 19,
    businessName: 'Brookside Child Care',
    contactName: 'Lena Morris',
    phone: '(816) 555-1019',
    email: 'lena@brooksidecare.example',
    website: 'https://brooksidecare.example',
    facebookPage: 'https://facebook.com/brooksidecare',
    address: '6322 Brookside Plaza',
    city: 'Kansas City',
    state: 'MO',
    industry: 'Education',
    currentWebsiteQuality: 'Average',
    hasWebsite: 'Yes',
    hasFacebookPage: 'Yes',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Enrollment lead flow',
    suggestedOffer: 'Enrollment funnel',
    estimatedDealValue: 2000,
    leadSource: 'Facebook',
    leadStatus: 'Contacted',
    priority: 'Warm',
    lastContactedDate: '2026-05-23',
    nextFollowUpDate: '2026-05-28',
    notes: 'Needs parent inquiry workflow.',
    painPoints: 'Paper based intake',
    personalizedPitch: 'Simple digital enrollment sequence.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'Medium',
    websitePackageInterest: 'Medium',
    crmPackageInterest: 'Medium',
    tags: ['education'],
    createdDate: '2026-05-17 10:20:00',
    updatedDate: '2026-05-23 14:58:00',
  },
  {
    id: 20,
    businessName: 'Pioneer Solar Solutions',
    contactName: 'Grace Nolan',
    phone: '(913) 555-1020',
    email: 'grace@pioneersolar.example',
    website: 'https://pioneersolar.example',
    facebookPage: 'https://facebook.com/pioneersolar',
    address: '9200 Renner Blvd',
    city: 'Lenexa',
    state: 'KS',
    industry: 'General Service',
    currentWebsiteQuality: 'Good',
    hasWebsite: 'Yes',
    hasFacebookPage: 'Yes',
    googleBusinessProfile: 'Claimed',
    serviceOpportunity: 'Estimator and lead nurturing',
    suggestedOffer: 'Full service package',
    estimatedDealValue: 7600,
    leadSource: 'Google',
    leadStatus: 'Won',
    priority: 'Urgent',
    lastContactedDate: '2026-05-26',
    nextFollowUpDate: '',
    notes: 'Signed annual agreement.',
    painPoints: 'Long sales cycle',
    personalizedPitch: 'Pipeline plus nurture automation.',
    demoWebsiteUrl: '',
    crmDemoUrl: '',
    marketingPackageInterest: 'High',
    websitePackageInterest: 'High',
    crmPackageInterest: 'High',
    tags: ['solar', 'won'],
    createdDate: '2026-05-02 12:00:00',
    updatedDate: '2026-05-26 16:10:00',
  },
];

const SORT_MAP: Record<string, keyof Lead> = {
  businessName: 'businessName',
  contactName: 'contactName',
  address: 'address',
  city: 'city',
  state: 'state',
  leadStatus: 'leadStatus',
  priority: 'priority',
  industry: 'industry',
  estimatedDealValue: 'estimatedDealValue',
  createdDate: 'createdDate',
  updatedDate: 'updatedDate',
  nextFollowUpDate: 'nextFollowUpDate',
  lastContactedDate: 'lastContactedDate',
};

function toText(value: unknown) {
  return String(value ?? '').toLowerCase();
}

function scorePriority(priority: Lead['priority']) {
  if (priority === 'Urgent') return 4;
  if (priority === 'Hot') return 3;
  if (priority === 'Warm') return 2;
  return 1;
}

function inMonth(value: string, monthPrefix: string) {
  if (!value) return false;
  return value.startsWith(monthPrefix);
}

export function getMockLeads(): Lead[] {
  return [...MOCK_LEADS];
}

export function getMockLeadById(id: number): Lead | undefined {
  return MOCK_LEADS.find((lead) => lead.id === id);
}

export function getFilteredMockLeads(query: LeadQuery): Lead[] {
  const search = toText(query.search);
  const status = query.status || '';
  const priority = query.priority || '';
  const city = toText(query.city);
  const state = toText(query.state);
  const industry = query.industry || '';
  const sort = query.sort || 'createdDate';
  const dir = query.dir === 'asc' ? 1 : -1;

  const filtered = MOCK_LEADS.filter((lead) => {
    if (search) {
      const blob = [lead.businessName, lead.contactName, lead.phone, lead.city, lead.industry].map(toText).join(' ');
      if (!blob.includes(search)) return false;
    }
    if (status && lead.leadStatus !== status) return false;
    if (priority && lead.priority !== priority) return false;
    if (city && !toText(lead.city).includes(city)) return false;
    if (state && !toText(lead.state).includes(state)) return false;
    if (industry && lead.industry !== industry) return false;
    return true;
  });

  const key = SORT_MAP[sort] || 'createdDate';

  filtered.sort((a, b) => {
    const av = a[key];
    const bv = b[key];

    if (key === 'priority') {
      return (scorePriority(av as Lead['priority']) - scorePriority(bv as Lead['priority'])) * dir;
    }

    if (typeof av === 'number' || av === null || typeof bv === 'number' || bv === null) {
      const an = Number(av ?? 0);
      const bn = Number(bv ?? 0);
      return (an - bn) * dir;
    }

    return String(av ?? '').localeCompare(String(bv ?? '')) * dir;
  });

  return filtered;
}

export function buildMockDashboardStats(): DashboardStats {
  const today = new Date().toISOString().slice(0, 10);
  const thisMonth = today.slice(0, 7);

  const totalLeads = MOCK_LEADS.length;
  const newLeads = MOCK_LEADS.filter((l) => l.leadStatus === 'New').length;
  const contactedLeads = MOCK_LEADS.filter((l) =>
    ['Contacted', 'No answer', 'Interested', 'Follow up needed', 'Meeting scheduled', 'Proposal sent'].includes(l.leadStatus)
  ).length;
  const interestedLeads = MOCK_LEADS.filter((l) => l.leadStatus === 'Interested').length;
  const demoSentLeads = MOCK_LEADS.filter((l) => l.leadStatus === 'Demo website sent').length;
  const followUpDueToday = MOCK_LEADS.filter((l) =>
    l.nextFollowUpDate && l.nextFollowUpDate <= today && !['Won', 'Lost', 'Not a fit'].includes(l.leadStatus)
  ).length;
  const wonDeals = MOCK_LEADS.filter((l) => l.leadStatus === 'Won').length;
  const lostDeals = MOCK_LEADS.filter((l) => l.leadStatus === 'Lost').length;

  const monthlyEstimatedValue = MOCK_LEADS.reduce((sum, lead) => {
    if (['Lost', 'Not a fit'].includes(lead.leadStatus)) return sum;
    if (!lead.estimatedDealValue || lead.estimatedDealValue <= 0) return sum;
    if (!inMonth(lead.createdDate, thisMonth)) return sum;
    return sum + lead.estimatedDealValue;
  }, 0);

  const wonThisMonthValue = MOCK_LEADS.reduce((sum, lead) => {
    if (lead.leadStatus !== 'Won') return sum;
    if (!lead.estimatedDealValue || lead.estimatedDealValue <= 0) return sum;
    if (!inMonth(lead.updatedDate, thisMonth)) return sum;
    return sum + lead.estimatedDealValue;
  }, 0);

  const hotLeads = getFilteredMockLeads({}).filter((l) => ['Hot', 'Urgent'].includes(l.priority) && !['Won', 'Lost', 'Not a fit'].includes(l.leadStatus)).slice(0, 5);
  const upcomingFollowUps = getFilteredMockLeads({}).filter((l) => l.nextFollowUpDate && l.nextFollowUpDate >= today && !['Won', 'Lost', 'Not a fit'].includes(l.leadStatus)).sort((a, b) => a.nextFollowUpDate.localeCompare(b.nextFollowUpDate)).slice(0, 8);

  const recentActivity: Activity[] = MOCK_LEADS.slice(0, 10).map((lead, index) => ({
    id: index + 1,
    leadId: lead.id,
    type: 'note',
    description: `Followed up with ${lead.contactName}`,
    createdDate: lead.updatedDate,
    businessName: lead.businessName,
  }));

  return {
    totalLeads,
    newLeads,
    contactedLeads,
    interestedLeads,
    demoSentLeads,
    followUpDueToday,
    wonDeals,
    lostDeals,
    monthlyEstimatedValue,
    wonThisMonthValue,
    hotLeads,
    recentActivity,
    upcomingFollowUps,
    routesToday: 0,
    stopsToday: 0,
    completedRoutesThisMonth: 0,
    stopsCompletedThisMonth: 0,
  };
}
